trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

# Java setup
- task: UseJavaVersion@1
  inputs:
    versionSpec: '11'
    architecture: 'x64'

# SonarQube prepare
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'SonarQube-Service'
    scannerMode: 'Other'
    configMode: 'manual'
    cliProjectKey: 'monolith-app'
    cliProjectName: 'monolith-app'
    cliSources: '.'

# Build + Scan
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean verify sonar:sonar'

# Publish result
- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'