trigger:
- master 

pool:
  vmImage: ubuntu-latest

variables:
  imageName: monolith-app
  acrName: monojavaprojet1
  imageTag: $(Build.BuildId)

steps:

# Step 1: Build JAR using Maven (skip Liquibase and tests)
- task: Maven@4
  inputs:
    pomFile: 'pom.xml'
    goals: 'clean package'
    options: '-Pskip-liquibase -DskipTests'

# Step 2: Build Docker Image
- script: |
    docker build -t $(imageName):$(imageTag) .
  displayName: Build Docker Image

# Step 3: Login to Azure Container Registry
- task: Docker@2
  inputs:
    command: login
    containerRegistry: 'ACR-Service-Connection'

# Step 4: Tag Docker Image for ACR
- script: |
    docker tag $(imageName):$(imageTag) $(acrName).azurecr.io/$(imageName):$(imageTag)
  displayName: Tag Image

# Step 5: Push Docker Image to ACR
- script: |
    docker push $(acrName).azurecr.io/$(imageName):$(imageTag)
  displayName: Push Image