trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  imageName: monolith-app
  acrName: monojavaprojet1
  imageTag: $(Build.BuildId)

steps:

# ✅ Step 1: Install Java
- task: UseJavaVersion@1
  inputs:
    versionSpec: '11'
    architecture: 'x64'

# ✅ Step 2: Build JAR using Maven
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    options: '-DskipTests'
    publishJUnitResults: true

# ✅ Step 3: Build & Push Docker Image to ACR (BEST PRACTICE)
- task: Docker@2
  inputs:
    command: buildAndPush
    repository: $(imageName)
    dockerfile: '**/Dockerfile'
    containerRegistry: 'ACR-Service-Connection'
    tags: |
      $(imageTag)
      latest
